Repository instrumentisto/baza, pull requests merged in 2022-07, with the labels that each got.

#6 Allow symlinks to be overwritten
  Cargo.lock
  Makefile
  e2e/Cargo.toml
  e2e/samples/ignucius.jpg
  e2e/tests/main.rs
  e2e/tests/s3/mod.rs
  e2e/tests/s3/put_object.feature
  lib/Cargo.toml
  lib/src/lib.rs
  src/main.rs
Labels: enhancement, k::design, k::api

#3 Impl helm chart
  .editorconfig
  .github/workflows/ci.yml
  Makefile
  helm/.editorconfig
  helm/baza/.helmignore
  helm/baza/Chart.yaml
  helm/baza/templates/NOTES.txt
  helm/baza/templates/_helpers.tpl
  helm/baza/templates/configmap.nginx.yaml
  helm/baza/templates/ingress.yaml
  helm/baza/templates/pvc.yaml
  helm/baza/templates/service.yaml
  helm/baza/templates/statefulset.yaml
  helm/baza/values.yaml
Labels: feature, k::deploy

#13 Setup releases on CI
  .github/workflows/ci.yml
  CHANGELOG.md
  Makefile
  README.md
  helm/baza/CHANGELOG.md
  helm/baza/Chart.yaml
  helm/baza/README.md
Labels: feature, k::toolchain
